export type ProviderType = 'idn' | 'ipp';

export interface ProviderProfile {
  id: string;
  name: string;
  type: ProviderType;
  annualBirths: number;
  states: string[];
  source: string;
}

export const US_PROVIDERS: ProviderProfile[] = [
  // ═══════════════════════════════════════════
  // IPP — Independent Physician Practices (19)
  // ═══════════════════════════════════════════
  {
    id: 'unitedhealth',
    name: 'UnitedHealth Group',
    type: 'ipp',
    annualBirths: 220000,
    states: ['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'kaiser',
    name: 'Kaiser Permanente',
    type: 'ipp',
    annualBirths: 116000,
    states: ['CA', 'OR', 'WA', 'CO', 'HI', 'GA', 'VA', 'MD'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'advocate-ipp',
    name: 'Advocate Health',
    type: 'ipp',
    annualBirths: 55400,
    states: ['IL', 'WI', 'NC', 'GA', 'AL', 'SC'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'intermountain',
    name: 'Intermountain Health',
    type: 'ipp',
    annualBirths: 37477,
    states: ['UT', 'ID', 'NV', 'CO', 'WY', 'MT', 'KS'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'upmc',
    name: 'UPMC',
    type: 'ipp',
    annualBirths: 25000,
    states: ['PA', 'NY', 'MD', 'VA'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'massgenbrigham',
    name: 'Mass General Brigham',
    type: 'ipp',
    annualBirths: 22000,
    states: ['MA'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'unitypoint',
    name: 'UnityPoint Health',
    type: 'ipp',
    annualBirths: 20000,
    states: ['IA', 'IL', 'WI'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'banner',
    name: 'Banner Health',
    type: 'ipp',
    annualBirths: 18123,
    states: ['AZ', 'CO', 'NE', 'NV', 'WY', 'CA'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'sentara',
    name: 'Sentara Health',
    type: 'ipp',
    annualBirths: 15400,
    states: ['VA', 'NC', 'AL'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'henryford',
    name: 'Henry Ford Health',
    type: 'ipp',
    annualBirths: 12662,
    states: ['MI'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'allina',
    name: 'Allina Health',
    type: 'ipp',
    annualBirths: 12050,
    states: ['MN', 'WI'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'medstar',
    name: 'MedStar Health',
    type: 'ipp',
    annualBirths: 10035,
    states: ['MD', 'DC'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'johnshopkins',
    name: 'Johns Hopkins Medicine',
    type: 'ipp',
    annualBirths: 10082,
    states: ['MD', 'FL'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'sanford',
    name: 'Sanford Health',
    type: 'ipp',
    annualBirths: 9000,
    states: ['SD', 'ND', 'MN', 'IA', 'NE', 'MT', 'WY'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'stlukes',
    name: "St. Luke's Health System",
    type: 'ipp',
    annualBirths: 7391,
    states: ['ID'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'wvu',
    name: 'WVU Medicine',
    type: 'ipp',
    annualBirths: 5693,
    states: ['WV', 'MD', 'VA', 'PA'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'geisinger',
    name: 'Geisinger Health',
    type: 'ipp',
    annualBirths: 4385,
    states: ['PA', 'NJ'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'mainehealth',
    name: 'MaineHealth',
    type: 'ipp',
    annualBirths: 3629,
    states: ['ME', 'NH'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'presbyterian',
    name: 'Presbyterian Health',
    type: 'ipp',
    annualBirths: 2940,
    states: ['NM'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },

  // ═══════════════════════════════════════════
  // IDN — Integrated Delivery Networks (35)
  // ═══════════════════════════════════════════
  {
    id: 'hca',
    name: 'HCA Healthcare',
    type: 'idn',
    annualBirths: 212000,
    states: ['TX','FL','TN','VA','CO','GA','SC','KS','IN','NV','NH','UT','ID','AK','NC','MO','LA','KY','MS','CA'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'commonspirit',
    name: 'CommonSpirit Health',
    type: 'idn',
    annualBirths: 85000,
    states: ['CA','TX','AZ','CO','NE','OH','WA','KY','NV','IA','TN','IL','MN','OR','WI','NJ','ND','KS','AR','IN','NM','WV','PA','CT'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'ascension',
    name: 'Ascension',
    type: 'idn',
    annualBirths: 75753,
    states: ['TX','FL','MI','WI','IN','TN','AL','OK','KS','NY','MD','IL','MN','MS','CT','DC','SC','LA','KY'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'advocate-idn',
    name: 'Advocate Health',
    type: 'idn',
    annualBirths: 65000,
    states: ['IL', 'WI', 'NC', 'GA', 'AL', 'SC'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'providence',
    name: 'Providence',
    type: 'idn',
    annualBirths: 60000,
    states: ['WA', 'OR', 'CA', 'AK', 'MT', 'TX'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'trinity',
    name: 'Trinity Health',
    type: 'idn',
    annualBirths: 50000,
    states: ['MI','OH','IN','IA','IL','ID','CA','NJ','NY','PA','MA','CT','GA','FL','MD','DE','NE','SD','OR','NC','SC','LA','AL','GA','MS'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'tenet',
    name: 'Tenet Healthcare',
    type: 'idn',
    annualBirths: 45000,
    states: ['TX','FL','CA','AZ','SC','AL','MA','MI','TN','IL','PA','GA','NC','MO','AR','MS','NJ','CT','CO','IN','OH','LA','NV','OK','VA','MD','WI','WA','KY','SD','NE','NM','NH','WV','IA','OR','ND','MT','KS','RI','WY','ID','DE'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'baylor',
    name: 'Baylor Scott & White Health',
    type: 'idn',
    annualBirths: 40000,
    states: ['TX'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'adventhealth',
    name: 'AdventHealth',
    type: 'idn',
    annualBirths: 40000,
    states: ['FL','CO','TX','GA','NC','WI','IL','KS','KY'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'uhs',
    name: 'Universal Health Services (UHS)',
    type: 'idn',
    annualBirths: 34900,
    states: ['TX','NV','DC','VA','PA','SC','FL','CA','IL','IN','GA','AL','DE','WV','OK','WY','AK','MS','MO','NJ','CT','MA','ND','SD','OH','MI','WI','IA','NE','KS','NM','AZ','UT','OR','WA','ID','MT','CO','AR','TN','KY','LA','NC'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'northwell',
    name: 'Northwell Health',
    type: 'idn',
    annualBirths: 30500,
    states: ['NY'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'corewell',
    name: 'Corewell Health',
    type: 'idn',
    annualBirths: 28000,
    states: ['MI'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'sutter',
    name: 'Sutter Health',
    type: 'idn',
    annualBirths: 26000,
    states: ['CA'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'northside',
    name: 'Northside Hospital',
    type: 'idn',
    annualBirths: 23000,
    states: ['GA'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'rwjbarnabas',
    name: 'RWJBarnabas Health',
    type: 'idn',
    annualBirths: 22000,
    states: ['NJ'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'uchealth',
    name: 'University of California Health',
    type: 'idn',
    annualBirths: 20000,
    states: ['CA'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'inova',
    name: 'Inova Health System',
    type: 'idn',
    annualBirths: 19225,
    states: ['VA'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'uchealth-co',
    name: 'UCHealth',
    type: 'idn',
    annualBirths: 18365,
    states: ['CO', 'WY', 'NE'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'prisma',
    name: 'Prisma Health',
    type: 'idn',
    annualBirths: 16942,
    states: ['SC', 'GA'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'clevelandclinic',
    name: 'Cleveland Clinic',
    type: 'idn',
    annualBirths: 15000,
    states: ['OH', 'FL', 'NV'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'mayo',
    name: 'Mayo Clinic',
    type: 'idn',
    annualBirths: 15000,
    states: ['MN', 'AZ', 'FL'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'baptistmemorial',
    name: 'Baptist Memorial Health',
    type: 'idn',
    annualBirths: 11850,
    states: ['TN', 'MS', 'AR'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'bjc',
    name: 'BJC HealthCare',
    type: 'idn',
    annualBirths: 11241,
    states: ['MO', 'IL', 'KS'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'ochsner',
    name: 'Ochsner Health',
    type: 'idn',
    annualBirths: 10860,
    states: ['LA', 'MS'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'integris',
    name: 'Integris Health',
    type: 'idn',
    annualBirths: 9200,
    states: ['OK'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'lifespan',
    name: 'Lifespan',
    type: 'idn',
    annualBirths: 8989,
    states: ['RI'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'baptisthealth',
    name: 'Baptist Health',
    type: 'idn',
    annualBirths: 12459,
    states: ['KY', 'IN'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'yalenewh',
    name: 'Yale New Haven Health',
    type: 'idn',
    annualBirths: 12200,
    states: ['CT', 'RI', 'NY'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'hawaiipacific',
    name: 'Hawaii Pacific Health',
    type: 'idn',
    annualBirths: 6200,
    states: ['HI'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'christianacare',
    name: 'ChristianaCare',
    type: 'idn',
    annualBirths: 6590,
    states: ['DE', 'PA', 'NJ', 'MD'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'iuhealth',
    name: 'Indiana University Health',
    type: 'idn',
    annualBirths: 5000,
    states: ['IN'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'uabmedicine',
    name: 'UAB Medicine',
    type: 'idn',
    annualBirths: 4000,
    states: ['AL'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'dartmouth',
    name: 'Dartmouth Health',
    type: 'idn',
    annualBirths: 2500,
    states: ['NH', 'VT'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'uvmhealth',
    name: 'UVM Health Network',
    type: 'idn',
    annualBirths: 2540,
    states: ['VT', 'NY'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
  {
    id: 'billings',
    name: 'Billings Clinic',
    type: 'idn',
    annualBirths: 1150,
    states: ['MT', 'WY'],
    source: 'U.S. Payer-Provider OB Landscape Report',
  },
];

export const US_TOTAL_BIRTHS = 3628934;

export const getProvidersByType = (type: ProviderType): ProviderProfile[] =>
  US_PROVIDERS.filter((p) => p.type === type);

export const getProviderById = (id: string): ProviderProfile | undefined =>
  US_PROVIDERS.find((p) => p.id === id);

export const getAggregateBirths = (type: ProviderType): number =>
  getProvidersByType(type).reduce((sum, p) => sum + p.annualBirths, 0);
